#!/usr/bin/awk -f

BEGIN{
    if(h == 1)
    {
	print "script takes in interASinterPoP generated by intraASInterPoP.awk and outputs the"
	print "probability of each latency, ignores -9999, which is iplane for unknown"
	exit;
	    
    }
    total = 0;
    UNKNOWNVAL = -9999

}

$3 != UNKNOWNVAL{
    dist[$3]++;
    total++;
}

END{
    for(element in dist){
	print element, dist[element]/total;
    }

}
